site_name: Soopace - Paper Reading
site_url: https://simonjisu.github.io/PaperReading/
repo_url: https://github.com/simonjisu/PaperReading

theme:
  name: "material"
  logo: img/logo/logo.png
  custom_dir: overrides
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.tracking
    - toc.follow

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - tags:
      tags_file: Reviews/index.md
  - search
  - section-index
  - literate-nav:
      nav_file: SUMMARY.md
      implicit_index: false
  # - glightbox:
  #      touchNavigation: true
  #      loop: false
  #      effect: none
  #      width: 100%
  #      height: 100%
  #      zoomable: true
  #      draggable: true

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/simonjisu
  analytics:
    provider: google
    property: G-LJESYTRE7M
extra_css:
  - stylesheets/extra.css